### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-final-mercarf#1]
Muy buen trabajo @mercarf!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 332 / 429
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > ATRIBUTOS: Todos los `a` deben tener el atributo `title`.
- [ ] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `title`.
- [x] HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un `nav`.
- [x] HTML > HERO: El texto del título del hero debe ser: Anonymous proxy.
- [x] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Looking through a window".
- [x] HTML > MÓDULO LOOKING: Debe haber un párrafo con el texto "Donec accumsan...".
- [x] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "3 reasons to purchase" que sea un `H2 - H6`.
- [x] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Lorem ipsum dolor sit amet, consecteur.".
- [x] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Curabitur ac erat".

- [ ] CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > `order`.
- [ ] CSS > TRANSICIONES: Debemos usar alguna transición CSS.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja dímelo cuanto antes por favor.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Anonymous** para buscar el hero. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by mercarf** [comment]
Hola Miguel,
A la hora de corregir las issues lo he hecho desde la rama nueva que creamos para mergear y cargar todo practicando con eso.
Además me he tomado la libertad de separar el header del hero que en el examen lo metí todo dentro del header

Respecto a las issues, He puesto el tick en las que he corregido (que la mayoría eran fallos de haber copiado el texto latín a mano y traspapelar alguna letra) pero luego hay otros que no termino de ver el error (como los dos ultimos)

El del "title" de los img no lo he hecho, por lo que hablamos en clase de que no siempre es necesario.

Espero que esté todo correcto, y muchas gracias por el examen y la entrevista. Lo disfruté mucho.

**Comment by migueldelmazo** [comment]
Hola @mercarf ,

Efectivamente estos:
- CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > order.
- CSS > TRANSICIONES: Debemos usar alguna transición CSS.

Son fallos míos, estoy investigando qué pasa... :(

Y también tienes razón en: El del "title" de los img no lo he hecho, por lo que hablamos en clase de que no siempre es necesario.

La política del autocorrector es que por si acaso cantamos el error. Y que sea la alumna y Miguel los que vean si realmente es un error. El autocorrector tiene ciertas limitaciones.

Gracias por mejorar el ejercicio.

**Comment by mercarf** [comment]
A ti por todos los tips, recomendaciones y sobre todo las correcciones. Sino no aprendería ni avanzaría. 
Intentaré seguir mejorándolo a medida que vayamos aprendiendo cosas nuevas. que por desgracia yo no puedo avanzar mas rápido de lo que vamos viendo. 

Toda crítica (constructiva) o reto a conseguir es bien recibido!
